web:
	build: .
	volumes:
		- .:/platzi
	link:
		- redis
	expose:
		- "5000"
redis:
	image: redis
lb:
	image: tutum/haproxy
	links:	
		- web
	ports::
		- "80:80"
	environment:
		- BACKEND_PORT=5000
		- BALANCE=roundrobin